### ISSUE TITLE
Unexpected item 'parameters › type_coverage'.

### ISSUE THREAD

**Issue by michaelzangerle** [TomasVotruba/type-coverage#10]
I am trying to set it up but ran into the following error

```
Unexpected item 'parameters › type_coverage'.
```

```
phpstan/phpdoc-parser        1.14.0 PHPDoc parser with support for nullable, intersection and generic types
phpstan/phpstan              1.9.14 PHPStan - PHP Static Analysis Tool
phpstan/phpstan-doctrine     1.3.23 Doctrine extensions for PHPStan
phpstan/phpstan-phpunit      1.2.2  PHPUnit extensions and rules for PHPStan
phpstan/phpstan-strict-rules 1.4.4  Extra strict and opinionated rules for PHPStan
phpstan/phpstan-symfony      1.2.16 Symfony Framework extensions and rules for PHPStan
tomasvotruba/type-coverage 0.0.9 Measure type coverage of your project
```

```
php 8.1.14
```

```neon
parameters:
    level: 8
    paths:
        - src
        - tests
    excludePaths:
        - tests/bootstrap.php
        - config/bootstrap.php
    symfony:
        container_xml_path: 'var/cache/dev/App_KernelDevDebugContainer.xml'
    scanDirectories:
        - var/cache/dev/Symfony/Config
    type_coverage:
        return_type: 50
        param_type: 30
        property_type: 70
        print_suggestions: false

includes:
    - vendor/phpstan/phpstan-doctrine/extension.neon
    - vendor/phpstan/phpstan-symfony/extension.neon
    - vendor/phpstan/phpstan-symfony/rules.neon
    - vendor/phpstan/phpstan-strict-rules/rules.neon
    - vendor/phpstan/phpstan-phpunit/extension.neon
```

I just ran the composer command + added the config in the readme to phpstan.neon. Did I miss something when installing / configuring it? :thinking:

**Comment by TomasVotruba** [comment]
Hi, do you have phpstan extension installer installed?

**Comment by michaelzangerle** [comment]
Hey @TomasVotruba. I don't know how I miss that something like https://github.com/phpstan/extension-installer exists in the first place but I guess that also explains why the line where you mention it in the readme didn't trigger me :see_no_evil: 

In case somebody else stumbles upon this: You can alternatively also solve this by adding the following line to your includes section in your phpstan.neon file:

```neon
includes:
    - vendor/tomasvotruba/type-coverage/config/extension.neon
```

Thank you Tomas :pray:

**Comment by scollovati** [comment]
Even if I have installed `phpstan/extension-installer` before this extension I still need to include that file.

Instead if I install PHPStan, PHPStan Extension installer and then this extension globally the issue does not arise.

**Comment by TomasVotruba** [comment]
Sometimes I have similar glitches. Running `composer install` helps, as only `composer install` triggers the extensions in some cases.

**Comment by scollovati** [comment]
Thanks Tomas. It's a subtle issue of https://github.com/phpstan/extension-installer as referenced here https://github.com/phpstan/extension-installer/issues/76#issuecomment-1657099451

It seems that if you have the installer installed globally and locally, the second one does not find the extensions locally. Very strange.

**Comment by TomasVotruba** [comment]
I see. I had similar issues with other dev packages, so I stopped using global scope. It also makes the project vendor locked to your local setup.

Also this leads to version conflicts.
