### ISSUE TITLE
PHP 8.2 support?

### ISSUE THREAD

**Issue by d8vjork** [TomasVotruba/type-coverage#16]
First of all, great work here! Love this idea of testing type coverage, actually implementing it on a massive software made with Laravel (started at Laravel 5.6, so pretty old, now using Laravel 9 & PHP 8.2 of course)

Thing is this is constrained to 8.0.* (tho main branch is updated to 8.1)

Is there any blockage for this? I mean... still can do `--ignore-platform-reqs` but not ideally to be done everytime

**Comment by TomasVotruba** [comment]
Hi,

thanks for the ping.

We've released version 0.1.1 version that supports 7.2 and 8.0+

https://github.com/TomasVotruba/type-coverage/releases/tag/0.1.1

**Comment by d8vjork** [comment]
@TomasVotruba Wow! That was fast. Thanks a lot
