### ISSUE TITLE
Less verbose output to prevent baseline regeneration

### ISSUE THREAD

**Issue by pionl** [TomasVotruba/type-coverage#20]
Hi @TomasVotruba,

thank you for the extension!

After adding to older code base and adding errors to the baseline (to check only new code at this moment - more fixups planned) we are forced to re-generate the baseline with quite a lot of changes.

Is it possible to force less verbose mode? Now we have over 4000 warnings on code that was not changed :)

Thank you for your time,

P.S: we could make the change, let me know where to change it and we can do it.

<img width="622" alt="Snímek obrazovky 2023-06-06 v 16 22 10" src="https://github.com/TomasVotruba/type-coverage/assets/1878831/3a6b804e-e901-4a77-abce-09b3bc703d1e">

<img width="1507" alt="Snímek obrazovky 2023-06-06 v 16 24 15" src="https://github.com/TomasVotruba/type-coverage/assets/1878831/eee85bf5-fdd2-4624-8eac-2c4574b38db0">

**Comment by TomasVotruba** [comment]
Hi, this is better used in a different way :)

Let's say we have a 70 % type coverage. Instead of ignoring errors, we always bump it to higher level then I have, e.g. 90 %. 

```diff
 # phpstan.neon
 parameters:
		type_coverage:
-				return_type: 70
+				return_type: 90
```

Then we run PHPStan:

```bash
vendor/bin/phpstan
```

Fix as many erros as we can. Let's say we reach the level of 80. 

Then instead of ignoring everything, we change it back to 80.

```diff
 # phpstan.neon
 parameters:
		type_coverage:
-				return_type: 90
+				return_type: 80
```

**Comment by verfriemelt-dot-org** [comment]
another option here would be to not print the actual percentages in the "error" but just let it state "missing param type" for example. the percentages can be printed as a hint. that would keep the changes on the baseline low while also providing useful information.
