### ISSUE TITLE
Feature: Allow PhpDoc return and parameter types to be considered as typed

### ISSUE THREAD

**Issue by orkhanahmadov** [TomasVotruba/type-coverage#27]
Since PHPStan has a parameter `treatPhpDocTypesAsCertain` and `true` by default, why not consider type coverage when the parameter/return type is already typed with PhpDoc?

**Comment by TomasVotruba** [comment]
Because docblock could still be invalid and give false feeling of type coverage. 
I would not use the type-coverage and this PHPStan config together as they have different use cases.

This package is to help you reach 100 % native type coverage.

**Comment by orkhanahmadov** [comment]
@TomasVotruba true and I agree for usual use-cases. But in some specific cases when you are using an interface or inheritance it is not always possible to type natively if parent class or interface itself is not typed. It basically forces you type `mixed` everywhere to reach 100% coverage. But using mixed confuses IDE and that 100% becomes a lie. I would argue that having correct type coverage with PhpDoc in those specific scenarios is still better than using `mixed`.
