### ISSUE TITLE
Problem with the message returned when type coverage tests fail

### ISSUE THREAD

**Issue by carlos-granados** [TomasVotruba/type-coverage#29]
I have a project which I was testing using this library. For return types, if I set the return type coverage level to 66 I get this message:

```
Out of 9930 possible return types, only 6551 - 66.0 % actually have it. Add more return types to get over 66
```

The problem here is that the message seems to imply that my actual coverage is 66.0% but it is actually 6551/9930 = 65.97%. If we are rounding we should round down so that we show a value that, if the user sets in the config, the tests will pass. Otherwise the message just looks weird and leaves you wondering what you did wrong.

Another problem is that if I use the new possibility to use floats and I set the value, for example, to 66.1 I get the same message. The "Add more return types to get over" part should use the float value, not the rounded value

**Comment by TomasVotruba** [comment]
Thanks :+1: 

Just a rough fix - could you verify it helps you use case?
https://github.com/TomasVotruba/type-coverage/pull/30

**Comment by carlos-granados** [comment]
This does not work OK, I commented on the PR.

Also this only fixes the first problem I reported. There is still the second problem

**Comment by carlos-granados** [comment]
This second problem can be solved by changing 
```
    public const ERROR_MESSAGE = 'Out of %d possible return types, only %d - %.1f %% actually have it. Add more return types to get over %d %%';
```

to

```
    public const ERROR_MESSAGE = 'Out of %d possible return types, only %d - %.1f %% actually have it. Add more return types to get over %s %%';
```

This will print the limit as you have configured it

**Comment by TomasVotruba** [comment]
Thanks :+1: Could you send PR for it?

**Comment by carlos-granados** [comment]
Done https://github.com/TomasVotruba/type-coverage/pull/31

**Comment by TomasVotruba** [comment]
Thanks :+1:
