### ISSUE TITLE
phpstan dependency

### ISSUE THREAD

**Issue by staabm** [TomasVotruba/type-coverage#4]
does this package really require `"phpstan/phpstan": "^1.9.3",`?

this is a pretty high bar. would e.g. `^1.9` or even `^1.8` be fine?

**Comment by TomasVotruba** [comment]
I always go for latest, co be compatible with PHPStan/Rector setup. E.g. last 1.9.2 has old phpdoc-parser with breaking docblocks.

**Comment by staabm** [comment]
its an issue for userland as the package cannot be installed in a project with only 1.9.2

**Comment by TomasVotruba** [comment]
That's expected. Bump to PHPStan 1.9.3

**Comment by staabm** [comment]
yeah sure, but why? you are limitting your user base without benefits?

**Comment by TomasVotruba** [comment]
The PHPStan 1.9.2 is buggy, see https://github.com/TomasVotruba/type-coverage/issues/4#issuecomment-1363830848
