### ISSUE TITLE
Feature Request: Measure Type-Coverage for Class constants

### ISSUE THREAD

**Issue by pableu** [TomasVotruba/type-coverage#40]
PHP 8.3 and later support declaring a type for PHP Class constants.

It's one of the easier changes to enforce because you can partially do it with rector and it's easier to add manually because the values are, well, constant ;-)

Could we extend this package to allow to require a minimal type coverage for class consts?

**Comment by TomasVotruba** [comment]
That's brilliant idea and makes sense :+1:   Would you like to add this one? :)

**Comment by pableu** [comment]
I'll give it a go this rainy weekend. I'll make a PR is if I get anywhere.
