### ISSUE TITLE
PhpStan 2.0 Support

### ISSUE THREAD

**Issue by eman1986** [TomasVotruba/type-coverage#47]
I upgraded to PhpStan 2.0 and see that this library does not yet it.

**Comment by binaryfire** [comment]
I'm also running into issues. Larastan requires PhpStan 2.0 so I'm unable to use both packages in projects. Any chance it could be bumped to v2?

**Comment by TomasVotruba** [comment]
We'll do upgrade for all packages at once. To make the upgrade path for end-users easy.
If all goes well, Rector 2.0 will be tagged on December 12th :tada: 

https://github.com/rectorphp/rector/issues/8815#issuecomment-2493467044

**Comment by morawcik** [comment]
So there is no option for faster dev/rc or something?

**Comment by SanderMuller** [comment]
I think this is now resolved with the release of 2.0, right?

**Comment by samsonasik** [comment]
Yes 👍
