### ISSUE TITLE
option to make the "issues" unignoreable

### ISSUE THREAD

**Issue by verfriemelt-dot-org** [TomasVotruba/type-coverage#6]
sometimes we are forced to regenerate our baseline this ended up "ignoring" the missed threshold regarding the type coverage. is it possible to make (optional would be fine) to make the typecoverage "issues" non-ignorable so that its always a conscious effort to update the values provided in the configuration of phpstan, rather then throwing them into the baseline?

**Comment by TomasVotruba** [comment]
Hi, what exactly do you mean? This package errors should never be ignored.

**Comment by verfriemelt-dot-org** [comment]
:thinking: okay so i just double checked it and now i am scratching my head.
_if_ you have reports about types missing like this one:

```
 ------ --------------------------------------------------------------------------------------------------------
  Line   N/A
 ------ --------------------------------------------------------------------------------------------------------
  -1     Out of 256 possible return types, only 100 % actually have it. Add more return types to get over 101 %
 ------ --------------------------------------------------------------------------------------------------------
```

and regenerate the baseline, this will be put into the baseline.

```diff
 $  git diff
diff --git a/phpstan.baseline.neon b/phpstan.baseline.neon
index ec07212..a22055c 100644
--- a/phpstan.baseline.neon
+++ b/phpstan.baseline.neon
@@ -1,5 +1,10 @@
 parameters:
        ignoreErrors:
+               -
+                       message: "#^Out of 256 possible return types, only 100 %% actually have it\\. Add more return types to get over 101 %%$#"
+                       count: 1
+                       path: N/A
+
```

this was what i am referring to, and wondered if we can make the "unignoreable" (as in: they trigger a message during baseline generation worded like this: "Some errors could not be put into baseline. Re-run PHPStan and fix them.")
while double checking this, i noticed that the baseline entry has no effect on the error reporting anyways, i am still getting even with the mentioned entry in the baseline:

```
 ------ --------------------------------------------------------------------------------------------------------
  Line   N/A
 ------ --------------------------------------------------------------------------------------------------------
  -1     Out of 256 possible return types, only 100 % actually have it. Add more return types to get over 101 %
 ------ --------------------------------------------------------------------------------------------------------
```

**Comment by TomasVotruba** [comment]
Congrats on full type coverage 🎉

> this was what i am referring to, and wondered if we can make the "unignoreable"

How can we make that happen? :)

**Comment by verfriemelt-dot-org** [comment]
[i think within phpstan those are tracked as errors](https://github.com/phpstan/phpstan-src/blob/1.9.x/src/Analyser/FileAnalyserResult.php#L29) and in turn are printed out here:

https://github.com/phpstan/phpstan-src/blob/1.9.x/src/Command/AnalyseCommand.php#L342-L349

but yeah, i quickly looked into this but found no obvious way to get to there from the collector ¯\\\_(ツ)_/¯
