### ISSUE TITLE
False positives for properties and parameters

### ISSUE THREAD

**Issue by enumag** [TomasVotruba/type-coverage#7]
I tried to get my type coverage to full 100% but it turns out there are some issues that can't be solved. Namely I can't add a type to a parameter or a property if a parent class doesn't have the type. Both come up for instance when adding custom constraints for symfony/validator:

```php
// missing property type
\Symfony\Component\Validator\Constraint::$errorNames
// missing paramerter type
\Symfony\Component\Validator\ConstraintValidatorInterface::validate($value, Constraint $constraint)
```

Since these are impossible to resolve I think they shouldn't be reported.

**Comment by TomasVotruba** [comment]
I'm not sure how the exact code looks like. We'll need a failing test fixture.

**Comment by enumag** [comment]
Okay so turns out that for parameters you can actually add the mixed type in child class which makes type-coverage shut up.

For properties this doesn't work but I managed to fix it by overriding `\Symfony\Component\Validator\Constraint::getErrorName()` method instead of the  `$errorNames` property.
