### ISSUE TITLE
github does not know the composer <-> github.com mapping

### ISSUE THREAD

**Issue by staabm** [TomasVotruba/type-coverage#8]
looking at the dependency graph of my project in 

https://github.com/FriendsOfREDAXO/rexstan/network/dependencies

![grafik](https://user-images.githubusercontent.com/120441/213151812-b2d70894-3168-4073-844a-a4a232ef77f3.png)

I get the feeling that - for some reason - dependabot does not know the mapping from the composer.org package and the github.com repo.

you can see that the package name is not linked to the github repo and also other github.com proprietary stuff like the sponsor button do not show up.

it works well for the `unused-public` and `cognitive-complexity` package though

**Comment by szepeviktor** [comment]
There seems to be no problem, it is hiding :)
https://packagist.org/packages/tomasvotruba/type-coverage.json

Maybe GitHub support will help.

**Comment by szepeviktor** [comment]
GitHub support wrote

> Thank you for contacting GitHub support. Thanks for bringing this up. I don't see where we have pulled this dependency in yet to be able to map it, so I have opened an issue with our engineers to look into why. Please let me know if there is anything else I can help you with.

**Comment by szepeviktor** [comment]
Now it is on the list twice.

![image](https://user-images.githubusercontent.com/952007/228927686-4ba88563-f425-4b52-b263-df07a0df80cc.png)

**Comment by TomasVotruba** [comment]
Thanks :+1:

**Comment by staabm** [comment]
I don't agree. when hovering the line in the table you can see tomasvotruba/type-coverage is not linked to the actual github repo, but other dependencies are linked

![grafik](https://user-images.githubusercontent.com/120441/229065047-a0e666c9-aed0-4c4f-98f4-64e1979408dd.png)

**Comment by staabm** [comment]
but since it seems to be a github.com bug, I am fine with leaving the issue closed

**Comment by szepeviktor** [comment]
> tomasvotruba/type-coverage is not linked

You're right.
