### ISSUE TITLE
Results sometimes lacking details

### ISSUE THREAD

**Issue by ajardin** [TomasVotruba/type-coverage#9]
Hello and thanks for your work! 😄

I had only one minor issue.  Basically, some of my normalizers ([example](https://github.com/ajardin/sandbox-phpstan/blob/main/src/Normalizer/HelloNormalizer.php)) did not define the type (`mixed`) of the first argument of the `supportsNormalization` and `normalize` methods. And the results of the analysis did not indicate which file was failing.

```
 2/2 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ ---------------------------------------------------------------------------------------------------
  Line   N/A
 ------ ---------------------------------------------------------------------------------------------------
  -1     Out of 5 possible param types, only 60 % actually have it. Add more param types to get over 100 %
 ------ ---------------------------------------------------------------------------------------------------



 [ERROR] Found 1 error

```

Here is a small snippet if you want to reproduce the issue.
```
git clone git@github.com:ajardin/sandbox-phpstan.git
cd sandbox-phpstan
composer install
./vendor/bin/phpstan
```

**Comment by osteel** [comment]
Having the same issue as reported [here](https://twitter.com/osteel/status/1636326313819602949)

**Comment by osteel** [comment]
@TomasVotruba that doesn't seem to be the current behaviour.

With this config:

```neon
type_coverage:
    return_type: 100
    param_type: 100
    property_type: 100
```

I get:

<img width="848" alt="image" src="https://user-images.githubusercontent.com/436467/225692999-d9c822e7-3dca-40b7-9166-e07a168d20c2.png">

And with this one:

```neon
type_coverage:
    return_type: 100
    param_type: 100
    property_type: 100
    print_suggestions: true
```

I get (truncated on the right-hand side):

<img width="848" alt="image" src="https://user-images.githubusercontent.com/436467/225693326-f21ce00a-df74-46c7-8048-2fbf93782c1e.png">

For information, I'm using v0.1.0 and the error is about the missing return type here:

```php
class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        // ...
    }
}
```

**Comment by TomasVotruba** [comment]
Exactly, that's ideal :)

**Comment by TomasVotruba** [comment]
Closing as answered.
